### ISSUE TITLE
Clarify encoding, endianness of multi-byte values in HPKE application info and AAD strings

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/ppm-specification#139]
We specify HPKE context construction and sealing like so:

```
enc, context = SetupBaseS(pk, "pda input share" || task_id || server_role)
payload = context.Seal(time || nonce || extensions, input_share)
```

We should be explicit about the encoding and endianness of these values. Since we use [TLS presentation language](https://datatracker.ietf.org/doc/html/rfc8446#section-3) on the wire, I think the natural thing is to use that encoding when constructing these strings. So `time` (which is a uint64 counting seconds since epoch start) should be big endian, `extensions` should be the TLS presentation language encoding of the `struct Extension`, and so on.

**Comment by cjpatton** [comment]
TLS-syntax specifies the byte encoding of anything represented in it, including endianness.

**Comment by tgeoghegan** [comment]
At the risk of being tediously pedantic: I think we should explicitly state that the TLS syntax encoding of various structs is what should go into application info and AAD strings, to rule out the possibility of implementations just `memcpy`ing a C struct in there, or a JSON string or something. I'm not sure what the IETF standard of pedantry is here though.

**Comment by ekr** [comment]
I tend to think this is too pedantic, but if necessary, I would just say "serialized".

**Comment by cjpatton** [comment]
I agree this is too pedantic, and I don't see a need to add the word "serialized".

**Comment by tgeoghegan** [comment]
Fair enough, I am closing this issue then.
