### ISSUE TITLE
Need LICENSE.md

### ISSUE THREAD

**Issue by ekr** [abetterinternet/ppm-specification#144]
Right now this is empty. I propose that we do CC-0. Assuming people agree, I'll update LICENSE.md

**Comment by stpeter** [comment]
CC0 seems fine, since the I-D will eventually just get licensed under IETF IPR rules anyway.

**Comment by stpeter** [comment]
Or we could do something like this: https://github.com/yaronf/I-D/blob/main/LICENSE.md (however, I'm not sure what the best practice is, I don't see anything about it in RFC 8874, and even repositories like https://github.com/quicwg/base-drafts don't have a LICENSE.md file).

**Comment by ekr** [comment]
What I'm trying to do here is have our initial submission actually have
broader terms than the IETF terms.

**Comment by stpeter** [comment]
Makes sense. Some folks seem to think that CC0 / PD / Unlicense doesn't stick in certain locales because you have to assert copyright first. CC-BY feels weird, too, because the question is "by whom" (just the spec authors?). I'll ask someone at Mozilla about it.

**Comment by stpeter** [comment]
If CC0 doesn't work, our resident expert at Mozilla suggested that we might consider WHATWG licensing (which is likely palatable to the relevant stakeholders):

> This work is licensed under a Creative Commons Attribution 4.0 International License. To the extent portions of it are incorporated into source code, such portions in the source code are licensed under the BSD 3-Clause License instead.
