### ISSUE TITLE
Consider allowing clients to upload mulitple reports in a single message to aggregators

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/ppm-specification#188]
Right now, an upload message from a client to an aggregator contains a single report (or two shares of a single report, in #174). I suspect there will be cases where a client will want to upload multiple reports in one HTTP transaction, especially deployments that use an intermediate client/client proxy/batching client. I believe we will need to define a PPM protocol message that allows multiple reports to support this.

**Comment by cjpatton** [comment]
This sounds like a duplicate of https://github.com/abetterinternet/ppm-specification/issues/64?

**Comment by tgeoghegan** [comment]
You're right, it is! I should have searched for existing issues before writing up a new one.
