### ISSUE TITLE
Do not require parsing aggregation messages before authenticating

### ISSUE THREAD

**Issue by BranLwyd** [abetterinternet/ppm-specification#202]
The interop target PR (#179) currently specifies that messages must be cryptographcially authenticated before they are interpreted:

> The last 32 bytes of each message is an HMAC-SHA256 tag computed over the serialized message excluding the tag field itself. The key that is used is the agg_auth_key shared by the aggregators and configured for the given task.
> 
> Upon receiving an AggregateReq message, an aggregator MUST verify the tag before interpreting the message's contents. If verification fails, it MUST abort and alert its peer with error "invalidHmac".

The HMAC key to use to perform verification is based on the task; the task is identified by an ID contained in the message. Therefore, currently the message must be interpreted before it can be authenticated. This is a problem because implementations both cannot follow the letter of the specification, and because requiring interpretation of message bytes before verification makes it more likely that implementations will be exposed to attacks from unauthenticated attackers based on bugs in the message parsing code.

Implementations should not have to parse authenticated messages before performing authentication.

Discussing with @cjpatton, @chris-wood, & @divergentdave, two strawman solutions were identified:

1) Include the task ID as an HTTP header. This is a relatively simple strategy, but would either move the task ID out of the message itself (losing binding of the message to a task), or duplicate the task ID in both the message & the header (increasing the amount of overhead per request).

2) Ensure that the task ID is at a specific byte offset in all authenticated messages, similar to the current arrangement that the authentication tag is the last 32 bytes of each message. For example, the task ID could be arranged to be the first 32 bytes of the message. Then authentication would be: read the task ID as the first 32 bytes and retrieve the HMAC key; verify the content based on the tag as the last 32 bytes & the retrieved key; if successful, parse the message. This strategy allows the message to keep its binding to the task without requiring duplication of information, but is somewhat more complex to specify & implement.

**Comment by divergentdave** [comment]
Here's a third proposal for how to handle HMAC authentication. I propose the following structure definitions:

```
struct {
  AggregationJobID job_id;
  opaque agg_param<0..2^16-1>;
  ReportShare seq<1..2^16-1>;
} AggregateInitReq;

struct {
  AggregationJobID job_id;
  Transition seq<1..2^16-1>;
} AggregateContinueReq;

struct {
  AggregateReqType msg_type;
  select (msg_type) {
    agg_init_req:  AggregateInitReq;
    agg_cont_req:  AggregateContinueReq;
  }
} AggregateReqInner;

struct {
  TaskID task_id;
  opaque inner<0..2^16-1>;
  opaque tag[32];
} AggregateReqOuter;

struct {
  Transition seq<1..2^16-1>;
} AggregateRespInner;

struct {
  opaque inner<0..2^16-1>;
  opaque tag[32];
} AggregateRespOuter;

struct {
  Interval batch_interval;
  uint64 report_count;
  opaque checksum[32];
} AggregateShareReqInner;

struct {
  TaskID task_id;
  opaque inner<0..2^16-1>;
  opaque tag[32];
} AggregateShareReqOuter;

struct {
  HpkeCiphertext encrypted_aggregate_share;
} AggregateShareResp;

struct {
  opaque inner<0..2^16-1>;
  opaque tag[32];
} AggregateShareRespOuter;
```

The specification text would say in each case that the HMAC tag is over the encoding of the preceding (one or two) structure elements, and the HMAC key is selected based on the `TaskID` in either the request structure itself, or the request corresponding to the response. The byte string contained by `AggregateReqOuter.inner` encodes a message of type `AggregateReqInner`, same with `AggregateRespOuter.inner` and `AggregateRespInner`, `AggregateShareReqOuter.inner` and `AggregateShareReqInner`, `AggregateShareRespOuter.inner` and `AggregateShareRespInner`.

Downsides: This way, the specification is a bit more verbose, messages will be two bytes longer for the additional length field, and various fields will have their effective length limits reduced slightly.
Upsides: The text "MUST verify the tag before interpreting the message's contents" will be much easier to follow, and we could get more specific, stating that the contents of `opaque inner<0..2^16-1>` must not be interpreted before verifying the tag over it and (sometimes) the task ID. There is no interaction with the HTTP layer request or response (aside from its body).

**Comment by BranLwyd** [comment]
The interop target now specifies request messages in a way that allows the task ID to be extracted without parsing the entire application-specific message -- the task ID is now always the first 32 bytes, which matches strawman solution (2) above.

We might still consider moving authentication parameters to the HTTP Authentication header later, but as far as I'm concerned that's a "nice-to-have" & is definitely not necessary for the interop pilot. I'm closing this bug as, as far as I'm concerned, the issue is resolved.
