### ISSUE TITLE
Mode to make proof optional 

### ISSUE THREAD

**Issue by siyengar** [abetterinternet/ppm-specification#45]
Some applications might not need as much protection against malicious users and might be okay with a malicious user changing the values by a larger amount.  They might be using Prio purely for privacy and might have other ways to guard against malicious inputs, for example by verify the user account or by attesting the application. 
It might be useful for the Validity proof to be optional depending on the application. This would reduce overheads perhaps of  communication between servers to validate the proofs and also in communication of the proofs from the client -> server.  

These applications could still benefit from:
1. the multi-server deployment model
2. AFE encoding specifications

**Comment by cjpatton** [comment]
This seems reasonable to me. Right now we have several pending design decisions floating around, so I'd like to suggest we wait on text until more of the protocol is settled.

**Comment by cjpatton** [comment]
Something to note here: if we have have a bit in the PA parameters that disables verification, we'll need to make sure this bit is explicitly authenticated.

**Comment by cjpatton** [comment]
Sounds good to me. Here is the issue for reference: https://github.com/cjpatton/vdaf/issues/20
